---
title: "Historical GOA data parameters"
author: "MACE"
date: "2024-05-23"
output: word_document
---

```{r setup, include=FALSE, error = TRUE, echo = FALSE}

rm(list=ls())

knitr::opts_chunk$set(echo = TRUE)

# Do you want to update the historical data from macebase?  This takes a while and should only be done if something significant has changed in the DB itself. 
#If you don't want to update it, you can access it by 
# save re-querying. NOTE: After you do all the queries, the output is saved here so we can know exactly what base data we used to
# make the report! This will also update the interpolated time series figure, which is quite time consuming as well.


update_datasets <- FALSE
#update_datasets <- TRUE



if (update_datasets == TRUE) {
  db_name <- "afsc-64"
  user_name <-  rstudioapi::askForPassword("Enter your Macebase2 username")
  pword <- rstudioapi::askForPassword("Enter your Macebase2 password")
}



zones = c(0)

#make this an rda file when it's tidy 

surface_historical_path = 'raw_data/parameters_wintergoa_length_age_time_series_1995_2008.csv'
#surface_historical_path = 'raw_data/parameters_wintergoa_length_age_time_series_1995_2001test.csv'
surface_historical = read.csv( surface_historical_path, header= TRUE, as.is = TRUE)



#load up yo necessary packages
#this package is used for managing conflicts for package function names
library(conflicted)
#this is for the database connections
library(DBI)
#misc stats needs
library(grid)
library(multimode)
#making tables, integrating with word docs
library(flextable)
library(ftExtra)
library(officedown)
library(officer)
 library(rmarkdown)
library(knitr)
# library(bibtex)
#mapping and spatial stuff
# library(gstat)
library(sf)
#library(RGeostats)
#opening SBE data
# library(oce)
#data munging, plotting, etc.
# library(gridGraphics)
# library(ggridges)
# library(ggpubr)
# library(ggrepel)
# library(RColorBrewer)
library(lubridate)
library(tidyverse)

#this is just because of conflicts between function names in different packages
#use the package 'conflicted' to be safe
#to be safe ensure this version is the only one that gets called:
conflict_prefer("summarize", "dplyr")
conflict_prefer("filter", "dplyr")
conflict_prefer("align", "flextable")
conflict_prefer("width", "flextable")


#if you want to explore any other function name conflicts, use conflict_scout()

#this just keeps a dplyr warning from the new 1.0 version from annoying folks- we always use 'group_by') default behavior
options(dplyr.summarise.inform = FALSE)

#call the functions we're using
source('scripts/get_historical_biomass_data_winter.R')
source('scripts/get_historical_AGE_biomass_data_winter.R')
source('scripts/get_event_and_interval_data_function_winterhistorical.R')
source('scripts/get_nice_region_names.R')
source('scripts/GetUpdateWinterGOA_function.R')


# #load shapefiles-bathymetery, land, some place labels and survey regions
# ak_land = st_read('shapefiles/alaska_land_NAD1983_HARN/alaska_land_NAD1983_HARN.shp')
# ak_labels = st_read('shapefiles/ak_area_labels_albers_alaska/ak_area_labels_albers_alaska.shp')
# management_regions = st_read('shapefiles/NMFS_management_areas_albers_alaska/NMFS_management_areas_albers_alaska.shp')
# wintersurveyregions = st_read('shapefiles/winter_survey_regions_BarnabasChiniak_NAD1983/winter_survey_regions_BarnabasChiniak_NAD1983.shp')
# 
# #project shapefiles
# management_regions = st_transform(management_regions, crs = 3338)
# ak_land = st_transform(ak_land, crs = 3338)
# winterpolygons = st_transform(wintersurveyregions, crs = 3338)

#load shapefiles-bathymetery, land, some place labels and survey regions
ak_land = st_read('shapefiles/alaska_land_NAD1983_HARN/alaska_land_NAD1983_HARN.shp')
ak_labels = st_read('shapefiles/ak_area_labels_albers_alaska/ak_area_labels_albers_alaska.shp')
management_regions = st_read('shapefiles/NMFS_management_areas_albers_alaska/NMFS_management_areas_albers_alaska.shp')
wintersurveyregions = st_read('shapefiles/winter_survey_regions_BarnabasChiniak_NAD1983/winter_survey_regions_BarnabasChiniak_NAD1983.shp')

#project shapefiles
management_regions = st_transform(management_regions, crs = 3338)
ak_land = st_transform(ak_land, crs = 3338)
winterpolygons = st_transform(wintersurveyregions, crs = 3338)





```




```{r update_winterGOA_data, echo = FALSE, message=FALSE, warning=TRUE}

#query MB2 for *pollock* biomass and numbers at length by interval for surveys from 2000- present
#we are going back *just* to 2000 because spatial data for 1994-1999 are a little shifty. 93-97 have weird monthly schedules
#and 99 has a horseshoe survey that makes everything tricky.


if (update_datasets == TRUE) {
  # open the database connection
  db <- dbConnect(odbc::odbc(), dsn = db_name, uid = user_name, pwd = pword)

  # run the queries to get/update data
  GetUpdateWinterGOA_function(surface_historical)

  # close the database connection
  dbDisconnect(db)
  
  query_run_time <- Sys.time()
  save(query_run_time, file = 'data/query_run_time.RData')

# 
#   # and load the dataset
#   load(file = paste0("data/", survey, "_GOA_summer_data.RData"))
}
 if (update_datasets == FALSE) {

data(PreSelectivityWinterGOA)
   
#load the last time the data were queried
   load(file = 'data/query_run_time.RData')
}
#
```

<!-- <!--provide a cover sheet highlights the basic parameters --> -->

**This report was created using data last queried at `r query_run_time`.**

We also used these historical surveys and parameters in comparisons:

```{r show_parameters, echo = FALSE, message=FALSE, warning=FALSE, results='asis'}
# make a basic table for the historical data parameters
summary_table <- flextable(surface_historical)

summary_table <- colformat_num(summary_table, j = c("Year", "surveys"), big.mark = "")

summary_table <- fit_to_width(summary_table, max_width = 7.8)

flextable_to_rmd(summary_table)
```
